"""add on delete cascading to the foreign keys to avoid exceptions

Revision ID: 52a083a54c97
Revises: 1ea31598181b
Create Date: 2025-01-27 03:27:58.623959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a083a54c97'
down_revision: Union[str, None] = '1ea31598181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cities_map_id_fkey', 'cities', type_='foreignkey')
    op.create_foreign_key('cities_map_id_fkey', 'cities', 'maps', ['map_id'], ['id'], ondelete='CASCADE')
    op.alter_column('connections', 'map_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('connections', 'parent_city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('connections', 'child_city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('connections_parent_city_id_fkey', 'connections', type_='foreignkey')
    op.drop_constraint('connections_child_city_id_fkey', 'connections', type_='foreignkey')
    op.create_foreign_key('connections_child_city_id_fkey', 'connections', 'cities', ['child_city_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('connections_parent_city_id_fkey', 'connections', 'cities', ['parent_city_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('routes_user_id_fkey', 'routes', type_='foreignkey')
    op.drop_constraint('routes_map_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key('routes_user_id_fkey', 'routes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('routes_map_id_fkey', 'routes', 'maps', ['map_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('routes_map_id_fkey', 'routes', type_='foreignkey')
    op.drop_constraint('routes_user_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key('routes_map_id_fkey', 'routes', 'maps', ['map_id'], ['id'])
    op.create_foreign_key('routes_user_id_fkey', 'routes', 'users', ['user_id'], ['id'])
    op.drop_constraint('connections_parent_city_id_fkey', 'connections', type_='foreignkey')
    op.drop_constraint('connections_child_city_id_fkey', 'connections', type_='foreignkey')
    op.create_foreign_key('connections_child_city_id_fkey', 'connections', 'cities', ['child_city_id'], ['id'])
    op.create_foreign_key('connections_parent_city_id_fkey', 'connections', 'cities', ['parent_city_id'], ['id'])
    op.alter_column('connections', 'child_city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('connections', 'parent_city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('connections', 'map_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('cities_map_id_fkey', 'cities', type_='foreignkey')
    op.create_foreign_key('cities_map_id_fkey', 'cities', 'maps', ['map_id'], ['id'])
    # ### end Alembic commands ###
