"""introduce user table for user management

Revision ID: 786e6d5137a2
Revises: 6724b2a75333
Create Date: 2024-12-09 22:56:33.200840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786e6d5137a2'
down_revision: Union[str, None] = '6724b2a75333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size_x', sa.Integer(), nullable=False),
    sa.Column('size_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_city_id', sa.Integer(), nullable=False),
    sa.Column('child_city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['parent_city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('connection')
    op.drop_table('map')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size_x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size_y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='map_pkey')
    )
    op.create_table('connection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('child_city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_city_id'], ['city.id'], name='connection_child_city_id_fkey'),
    sa.ForeignKeyConstraint(['parent_city_id'], ['city.id'], name='connection_parent_city_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='connection_pkey')
    )
    op.drop_table('connections')
    op.drop_table('users')
    op.drop_table('maps')
    # ### end Alembic commands ###
