"""initial tables creation

Revision ID: 9d47a1f5cb2c
Revises: 
Create Date: 2024-11-27 12:31:01.584313

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d47a1f5cb2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_city_id', sa.Integer(), nullable=False),
    sa.Column('child_city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['parent_city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection')
    op.drop_table('city')
    # ### end Alembic commands ###
