"""set map.name to unique and not nullable

Revision ID: c79a0d80c0ba
Revises: 52a083a54c97
Create Date: 2025-02-02 15:39:25.443079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79a0d80c0ba'
down_revision: Union[str, None] = '52a083a54c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('connections_map_id_fkey', 'connections', type_='foreignkey')
    op.create_foreign_key('connections_map_id_fkey', 'connections', 'maps', ['map_id'], ['id'], ondelete='CASCADE')
    op.alter_column('maps', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint('uq_maps_name', 'maps', ['name'])
    # ### end Alembic commands ###

    # Delete any existing entry with name 'skyrim' before renaming 'Skyrim'
    op.execute("DELETE FROM maps WHERE name = 'skyrim'")

    op.execute("UPDATE maps SET name = 'skyrim' WHERE name = 'Skyrim'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_maps_name', 'maps', type_='unique')
    op.alter_column('maps', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('connections_map_id_fkey', 'connections', type_='foreignkey')
    op.create_foreign_key('connections_map_id_fkey', 'connections', 'maps', ['map_id'], ['id'])

    # Rename 'skyrim' back to 'Skyrim'
    op.execute("UPDATE maps SET name = 'Skyrim' WHERE name = 'skyrim'")
    # ### end Alembic commands ###
